### ISSUE TITLE
Bug: Some Shops are overpriced

### ISSUE THREAD

**Issue by tokarevtokarev** [NekuSoul/ShopsOnly#8]
Hi, first of all: Great mod!
I find that some shops have way to high prices. F.e: I found a Shop in Stage 2 for over 700$ containing regular items.

**Comment by NekuSoul** [comment]
Thanks!

The prices are actually supposed to loosely mimic those of chests: A shop containing tier 1 (white) items costs the same as small chest, a tier 2 (green) shop costs the same as a large chest and the rare tier 3 shops (red) have the same base cost as the legendary chests that can be found in stage 4. I'm assuming you found a tier 3 shop, which is why the cost was so high.

Personally, I like how the costs are balanced, as it makes skipping an early tier 3 shop a valid choice if the items on offer aren't worth it.

That said, I'll take a look at adding some settings so that the costs can be customized for each tier of shops.

PS: If my guess was wrong and you're sure that it wasn't a tier 3 shop you ran into I'll have to take a deeper look into what happened.

**Comment by tokarevtokarev** [comment]
I’m sure that the shop contained Tier 1 items.
Same thing in stage 1 I found two shops with tier 1 items, that did cost 50$ instead of 25$

**Comment by tokarevtokarev** [comment]
Here is a Screenshot for clarification:

![20220309214440_1](https://user-images.githubusercontent.com/87748950/157533193-cb78a7f5-05d5-49bf-834a-10163072a460.jpg)
![20220309214445_1](https://user-images.githubusercontent.com/87748950/157533196-49b29e13-83a2-4ba2-85ab-713958d6815c.jpg)

**Comment by NekuSoul** [comment]
Yeah, I've just been trying to reproduce the bug and just found a shop just like that as well. Not sure yet why this is happening with the update, but I'll look into it.

**Comment by NekuSoul** [comment]
Took me a while to realize what's going on, but the actual issue was that the rarity of the shop items didn't get changed because the way shop items are chosen changed quite a bit with the update.

Anyway, I've found a way to fix it and it should work properly in version 3.0.2, which should be live on Thunderstore in a few minutes.
